# Generated by Django 5.0.6 on 2024-05-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("song_title", models.CharField(max_length=30)),
                ("song_artis", models.CharField(max_length=30)),
                ("song_album", models.CharField(max_length=30)),
                ("song_duration", models.DurationField()),
            ],
        ),
    ]
