# Generated by Django 5.0.6 on 2024-05-27 13:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stream", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="song",
            old_name="song_artis",
            new_name="song_artist",
        ),
    ]
