# Generated by Django 5.0.6 on 2024-05-27 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stream", "0002_rename_song_artis_song_song_artist"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("artist_name", models.CharField(max_length=30)),
                ("artist_nickname", models.CharField(max_length=30)),
                ("artist_date_of_birth", models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name="song",
            name="song_artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="stream.artist"
            ),
        ),
    ]
