# Generated by Django 5.0.6 on 2024-05-31 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stream", "0004_playlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="playlist_songs",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="stream.song",
            ),
        ),
    ]
