# Generated by Django 5.0.6 on 2024-05-31 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stream", "0006_playlist_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playlist",
            name="playlist_songs",
        ),
        migrations.AddField(
            model_name="playlist",
            name="playlist_songs",
            field=models.ManyToManyField(to="stream.song"),
        ),
    ]
